version: "3"
services:
  react-app:
    restart: always
    build:
      context: ./first_appp
      dockerfile: Dockerfile
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./first_appp/src:/app/src

  api-server:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: api-server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - ./backend:/app
  
networks:
  mern-app:
    driver: bridge
